export PATH="/usr/local/bin:$PATH"
export PATH="/opt/homebrew/bin:$PATH"
export PATH="/Users/robert/.bun/bin:$PATH"
export XDG_CONFIG_HOME="$HOME/.config"
export EDITOR="nvim"
export STARSHIP_CONFIG="$XDG_CONFIG_HOME/starship/starship.toml"
export HOMEBREW_NO_ENV_HINTS=true
export HOMEBREW_NO_EMOJI=1
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

if [[ "$TERM" == "xterm-kitty" ]]; then
    ICON_SRC="$HOME/Documents/Design/Icons/kitty.icns"
    ICON_DST="/Applications/Kitty.app/Contents/Resources/kitty.icns"

    if [[ -f "$ICON_SRC" && -f "$ICON_DST" ]]; then
        cp "$ICON_SRC" "$ICON_DST"
        touch "/Applications/Kitty.app"
    fi
fi

