
export PATH="/usr/local/bin:$PATH"
export PATH="/opt/homebrew/bin:$PATH"
export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"
export PATH="/Users/robert/.bun/bin:$PATH"
## Volta home dir
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"
## Main configs dir
export XDG_CONFIG_HOME="$HOME/.config"
## Set editor
export EDITOR="nvim"
## Starship config file
export STARSHIP_CONFIG="$XDG_CONFIG_HOME/starship/starship.toml"
## Homebrew Env Hints Off
export HOMEBREW_NO_ENV_HINTS=true
## NextJS Telemetry Opt Out
export NEXT_TELEMETRY_DISABLED=1
## Homebrew Emojis Off
export HOMEBREW_NO_EMOJI=1
## Java flags for compilers
export CPPFLAGS="-I/opt/homebrew/opt/openjdk/include"
## Chrome binary for dev testing
export CHROME_BIN="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
## Bat code hightlight theme
export BAT_THEME="Catppuccin Mocha"
## XQuartz Fallback
export DYLD_FALLBACK_LIBRARY_PATH="${DYLD_FALLBACK_LIBRARY_PATH}:/usr/lib:/usr/X11/lib"

if [[ "$TERM" == "xterm-kitty" ]]; then
    ICON_SRC="$HOME/Documents/Design/Icons/kitty.icns"
    ICON_DST="/Applications/Kitty.app/Contents/Resources/kitty.icns"

    if [[ -f "$ICON_SRC" && -f "$ICON_DST" ]]; then
        cp "$ICON_SRC" "$ICON_DST"
        touch "/Applications/Kitty.app"
    fi
fi

#   NVM Disabled for volta
#   export NVM_DIR="$HOME/.nvm"
#   [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
#   [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
