# Kitty Configuration

# Fonts
font_family      family='Monaspace Neon Var' variable_name=MonaspaceNeonVar style=MonaspaceNeonVar-Regular
bold_font        family='Monaspace Neon Var' variable_name=MonaspaceNeonVar style=MonaspaceNeonVar-Medium
italic_font      family='Monaspace Radon Var' variable_name=MonaspaceRadonVar style=MonaspaceRadonVar-Italic
bold_italic_font family='Monaspace Radon Var' variable_name=MonaspaceRadonVar style=MonaspaceRadonVar-MediumItalic

font_size 14.0
disable_ligatures never
modify_font underline_position 10
modify_font underline_thickness 150%
modify_font strikethrough_thickness 150%
#modify_font cell_width 110%
#narrow_symbols U+23fb-U+f1af0
underline_exclusion 0

# Cursor
cursor #cdd6f4
cursor_text_color       background
cursor_shape_unfocused hollow
cursor_shape underline
cursor_blink_interval 0.5 ease-in-out
cursor_underline_thickness 2.0
shell_integration no-cursor
cursor_trail 10
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 1

# Scrollback
scrollback_lines 5000
scrollback_indicator_opacity 0.6
scrollback_fill_enlarged_window none
touch_scroll_multiplier 1.0

# Mouse 
url_color #b4befe
url_prefixes file ftp ftps gemini git gopher http https irc ircs kitty mailto news sftp ssh
show_hyperlink_targets yes
underline_hyperlinks hover
strip_trailing_spaces never
select_by_word_characters @-./_~?&=%+#
detect_urls no

# Terminal Bell 
enable_audio_bell no 
window_alert_on_bell no
bell_on_tab "* "

# Window Layout
remember_window_size  no
initial_window_width  90c
initial_window_height 32c
window_border_width 0pt
draw_minimal_borders yes
window_margin_width 0
single_window_margin_width -1 
window_padding_width 5 8 
single_window_padding_width -1 
placement_strategy center
active_border_color     none
inactive_border_color   #ffffff
bell_border_color       #ffffff
inactive_text_alpha 0.6
hide_window_decorations titlebar-only
close_on_child_death yes
macos_quit_when_last_window_closed yes
confirm_os_window_close -1 count-background

# OS Window titlebar colors
macos_titlebar_color background
macos_show_window_title_in none 

# Tab bar
tab_bar_min_tabs 2
tab_switch_strategy left
tab_bar_style powerline
tab_powerline_style slanted
tab_title_max_length 16
tab_bar_margin_width 8
tab_bar_margin_color none
tab_bar_align left
tab_bar_background none
active_tab_font_style   bold
inactive_tab_font_style bold
tab_bar_margin_height 0.0 0.0
tab_title_template "{title[title.rfind('/')+1:]}{tab.progress_percent}{'  ' if num_windows > 1 else ''}"
active_tab_foreground   #1e1e2e
active_tab_background   #cdd6f4
inactive_tab_foreground #9399b2
inactive_tab_background #1e1e2e

# Color Scheme
foreground              #cdd6f4
background              #1e1e2e
selection_foreground    #1e1e2e
selection_background    #f5e0dc

# Colors for marks (marked text in the terminal)
mark1_foreground #1e1e2e
mark1_background #b4befe
mark2_foreground #1e1e2e
mark2_background #cba6f7
mark3_foreground #1e1e2e
mark3_background #74c7ec

# The 16 terminal colors

# black
color0 #45475a
color8 #585b70

# red
color1 #f38ba8
color9 #f38ba8

# green
color2  #a6e3a1
color10 #a6e3a1

# yellow
color3  #f9e2af
color11 #f9e2af

# blue
color4  #89b4fa
color12 #89b4fa

# magenta
color5  #f5c2e7
color13 #f5c2e7

# cyan
color6  #94e2d5
color14 #94e2d5

# white
color7  #bac2de
color15 #a6adc8

